a=int(input())
b=int(input())
c=int(input())
c=(c+a*2+b*3)/6
if c>=9: print("Xuat sac")
elif c>=8: print("Gioi")
elif c>=7: print("Kha")
elif c>=6: print("Trung binh Kha")
elif c>=5: print("Trung binh")
elif c>=3: print("Yeu")
else: print("Kem")